/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary':                  '#3b82f6',
        'primary-dim':              '#60a5fa',
        'primary-container':        '#2563eb',
        'primary-fixed':            '#3b82f6',
        'primary-fixed-dim':        '#5391ff',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#002150',
        'on-primary-fixed':         '#000000',
        'on-primary-fixed-variant': '#002a62',
        'inverse-primary':          '#005bc4',

        'secondary':                '#8097ff',
        'secondary-dim':            '#8097ff',
        'secondary-container':      '#213da1',
        'secondary-fixed':          '#c7cfff',
        'secondary-fixed-dim':      '#b4c1ff',
        'on-secondary':             '#00175f',
        'on-secondary-container':   '#c5ceff',
        'on-secondary-fixed':       '#00278f',
        'on-secondary-fixed-variant':'#2d48ac',

        'tertiary':                 '#fbabff',
        'tertiary-dim':             '#e28ce9',
        'tertiary-container':       '#f199f7',
        'tertiary-fixed':           '#f199f7',
        'tertiary-fixed-dim':       '#e28ce9',
        'on-tertiary':              '#691d74',
        'on-tertiary-container':    '#5e106a',
        'on-tertiary-fixed':        '#3e0047',
        'on-tertiary-fixed-variant':'#681c73',

        'error':                    '#ff716c',
        'error-dim':                '#d7383b',
        'error-container':          '#9f0519',
        'on-error':                 '#490006',
        'on-error-container':       '#ffa8a3',

        'surface':                  '#060e20',
        'surface-dim':              '#060e20',
        'surface-bright':           '#1f2b49',
        'surface-container-lowest': '#000000',
        'surface-container-low':    '#091328',
        'surface-container':        '#0f1930',
        'surface-container-high':   '#141f38',
        'surface-container-highest':'#192540',
        'surface-variant':          '#192540',
        'surface-tint':             '#3b82f6',
        'inverse-surface':          '#faf8ff',

        'background':               '#060e20',
        'on-background':            '#dee5ff',
        'on-surface':               '#dee5ff',
        'on-surface-variant':       '#a3aac4',
        'inverse-on-surface':       '#4d556b',

        'outline':                  '#6d758c',
        'outline-variant':          '#40485d',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body':     ['Inter', 'sans-serif'],
        'label':    ['Inter', 'sans-serif'],
        'sans':     ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'sm':    '0.125rem',
        'md':    '0.25rem',
        'lg':    '0.375rem',
        'xl':    '0.5rem',
        '2xl':   '0.75rem',
        'full':  '9999px',
      },
    },
  },
  plugins: [],
}
